AllCops:
  Exclude:
    - 'Gemfile'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 30

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
